# Generated by Django 4.0.4 on 2022-04-27 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ProductId', models.AutoField(primary_key=True, serialize=False)),
                ('ShopId', models.IntegerField(default=None)),
                ('NameProduct', models.CharField(max_length=25)),
                ('ActivProduct', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('ShopId', models.AutoField(primary_key=True, serialize=False)),
                ('UserId', models.IntegerField(default=None)),
                ('NameShop', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('Email', models.EmailField(max_length=25, unique=True)),
                ('Pass', models.CharField(max_length=30)),
            ],
        ),
    ]
